import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu/Menu";
import ExploreTrending from "@/components/explore/ExploreTrending";

const links = [
  {href:"/" , title:"Inicio"},
  {href:"/explore", title:"Explorar"},
  {href:"/users/leia", title: "Mi Perfil"}
]

const montserrat = Montserrat({ 
  subsets: ["latin"],
  variable: '--font-montserrat'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body>
        <Menu links={links}/>
        {children}
      </body>
    </html>
  );
}
